import React from "react";
import Image from "next/image";
import TeamImage from "../../assets/teams.png";
import HandsImage from "../../assets/hands.png";

export const metadata = {
  title: "Create About",
  description: "Generated by create next app",
};


export default function AboutPage() {
  return (
    <div className="container max-w-8xl mx-auto relative z-10 px-5 lg:px-12">
      {/* Mission & Vision */}
      <section className="p-8 grid grid-cols-1 md:grid-cols-2 gap-8 bg-gray-100 m-10">
        <div>
          <h3 className="text-sm font-bold text-gray-500">OUR MISSION</h3>
          <h2 className="text-xl font-bold">Creating valuable content for creatives all around the world</h2>
          <p className="text-gray-600 mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, maxime in aliquid necessitatibus laborum dicta quae veniam magni sit ullam, quaerat eum! Sint, quas voluptatum culpa dolore nemo, officiis possimus nesciunt architecto laudantium quo expedita magni. Cum aspernatur perspiciatis modi.</p>
        </div>
        <div>
          <h3 className="text-sm font-bold text-gray-500">OUR VISION</h3>
          <h2 className="text-xl font-bold">A platform that empowers individuals to improve</h2>
          <p className="text-gray-600 mt-2">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, maxime in aliquid necessitatibus laborum dicta quae veniam magni sit ullam, quaerat eum! Sint, quas voluptatum culpa dolore nemo, officiis possimus nesciunt architecto laudantium quo expedita magni. Cum aspernatur perspiciatis modi.</p>
        </div>
      </section>

      {/* Team Section */}
      <section className="p-8 flex flex-col md:flex-row items-center gap-8">
        <div className="md:w-1/2">
          <h2 className="text-2xl font-bold">Our team of creatives</h2>
          <p className="text-2xl font-medium text-black ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, eius?</p>
          <p className="mt-2 text-gray-600">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, maxime in aliquid necessitatibus laborum dicta quae veniam magni sit ullam, quaerat eum! Sint, quas voluptatum culpa dolore nemo, officiis possimus nesciunt architecto laudantium quo expedita magni. Cum aspernatur perspiciatis modi.</p>
        </div>
        <div className="md:w-1/2 relative">
          <Image src={HandsImage} alt="Team Hands" className="rounded-lg shadow-lg" />
          <div className="absolute top-0 left-0 bg-yellow-400 w-12 h-12 rounded-full"></div>
        </div>
      </section>

      {/* Blog Intro */}
      <section className="p-8 flex flex-col md:flex-row items-center gap-8">
        <div className="md:w-1/2">
          <Image src={TeamImage} alt="Team Discussion" className="rounded-lg shadow-lg" />
        </div>
        <div className="md:w-1/2">
          <h2 className="text-2xl font-bold">Why we started this Blog</h2>
          <p className="text-2xl font-medium text-black ">Lorem ipsum dolor sit amet consectetur adipisicing elit. Maiores, eius?</p>
          <p className="mt-2 text-gray-600">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Tempore, maxime in aliquid necessitatibus laborum dicta quae veniam magni sit ullam, quaerat eum! Sint, quas voluptatum culpa dolore nemo, officiis possimus nesciunt architecto laudantium quo expedita magni. Cum aspernatur perspiciatis modi.</p>
        </div>
      </section>
    </div>
  );
}
