import React from "react";
import Image from "next/image";
import HeroImg from "../assets/hero.png";
import Women from "../assets/women.png"
import Team from "../assets/team.png"
import Boy from "../assets/boy.png"
import Link from 'next/link'
import { IoBarChartOutline, IoBusinessSharp } from "react-icons/io5";
import { GoRocket } from "react-icons/go";
import { VscRobot } from "react-icons/vsc";

export const metadata = {
  title: "Create Finsweet",
  description: "Generated by create next app",
};


function HomePages() {
  const categories = [
    { id: 1, name: "Business", icon: <IoBusinessSharp />, desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit." },
    { id: 2, name: "Startup", icon: <GoRocket />, desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit." },
    { id: 3, name: "Economy", icon: <IoBarChartOutline />, desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit." },
    { id: 4, name: "Technology", icon: <VscRobot />, desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit." },
  ]
  return (
    <>
      <section className="relative w-full h-[500px] bg-gray-900 text-white flex items-center">
        <div className="absolute inset-0">
          <Image
            src={HeroImg}
            alt="Background"
            fill
            style={{ objectFit: "cover" }}
            quality={100}
          />
        </div>

        <div className="container max-w-8xl mx-auto relative z-10 px-5 lg:px-12">
          <div className="w-[50%]">
            <p className="text-sm text-gray-400 uppercase">
              Posted on <span className="font-bold text-white">Startup</span>
            </p>
            <h1 className="text-5xl font-bold mt-2 leading-tight">
              Step-by-step guide to choosing great font pairs
            </h1>
            <p className="text-sm text-gray-300 mt-4">
              By <span className="text-yellow-500">James West</span> | May 23, 2022
            </p>
            <p className="text-gray-400 mt-4 leading-relaxed">
              Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
            </p>
            <Link href="/blog">  <button className="bg-yellow-500 text-black px-6 py-3 mt-6 rounded-md font-medium hover:bg-yellow-600 transition duration-300 ease-in-out">
              Read More &gt;
            </button></Link>
          </div>
        </div>
      </section>
      <div className="container max-w-8xl mx-auto  px-5 lg:px-12 py-5">
        <h1 className="text-4xl font-bold text-black">Popular blogs</h1>
        <div className="mt-10 flex items-center justify-between">
          <Link href="/blog">
            <div className="w-[94%]">
              <Image className="w-full h-auto" src={Women} alt="women" />
              <small className="text-lg text-gray-700">By John Doe   l   Aug 23, 2021 </small>
              <h1 className="text-2xl mt-3 text-black font-bold">A UX Case Study Creating a Studious Environment for Students: </h1>
              <p className="text-lg mt-3">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            </div>
          </Link>
          <Link href="/blog">
            <div className="w-[94%]">
              <Image className="w-full h-auto" src={Team} alt="team" />
              <small className="text-lg text-gray-700">By John Doe   l   Aug 23, 2021 </small>
              <h1 className="text-2xl mt-3 text-black font-bold">A UX Case Study Creating a Studious Environment for Students: </h1>
              <p className="text-lg mt-3">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            </div>
          </Link>
          <Link href="/blog">
            <div className="w-[94%]">
              <Image className="w-full h-auto" src={Boy} alt="boy" />
              <small className="text-lg text-gray-700">By John Doe   l   Aug 23, 2021 </small>
              <h1 className="text-2xl mt-3 text-black font-bold">A UX Case Study Creating a Studious Environment for Students: </h1>
              <p className="text-lg mt-3">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.</p>
            </div>
          </Link>
        </div>
        <hr className="mt-10 bg-gray-300 h-0.5  w-full border-none" />
      </div>
      <div className="container max-w-8xl mx-auto  px-5 lg:px-12 py-5">
        <h1 className="text-4xl font-bold text-black text-center">Choose A Catagory</h1>
        <div className="mt-10 flex items-center justify-between gap-4">
          {categories.map((category) => (
            <div key={category.id} className="w-full">
              <Link href="/categories">
                <div className="p-6 border rounded-lg bg-white hover:bg-gray-100 cursor-pointer transition-all">
                  <div className="mb-3">{category.icon}</div>
                  <h2 className="text-2xl font-bold">{category.name}</h2>
                  <p className="text-sm font-medium">{category.desc}</p>
                </div>
              </Link>
            </div>
          ))}
        </div>

      </div>
      <hr className="mt-10 bg-gray-300 h-0.5  w-full border-none" />
    </>
  );
}

export default HomePages;
