import React from "react";


export const metadata = {
  title: "Create Register",
  description: "Generated by create next app",
};


export default function RegisterPage() {
  return (
    <div className="w-full flex flex-col items-center justify-center min-h-[72vh] bg-gray-100">
      {/* Register Section */}
      <section className="p-8 flex flex-col items-center">
        <h2 className="text-3xl font-bold mb-6">Register</h2>
        <div className="w-full max-w-md">
          <input type="text" placeholder="Firstname" className="w-full p-3 border border-gray-300 rounded-md mb-4" />
          <input type="text" placeholder="Lastname" className="w-full p-3 border border-gray-300 rounded-md mb-4" />
          <input type="text" placeholder="Username" className="w-full p-3 border border-gray-300 rounded-md mb-4" />
          <input type="password" placeholder="Password" className="w-full p-3 border border-gray-300 rounded-md mb-4" />
          <input type="password" placeholder="Confirm password" className="w-full p-3 border border-gray-300 rounded-md mb-6" />
          <button className="w-full p-3 bg-yellow-400 text-black font-bold rounded-md">Register</button>
        </div>
      </section>
    </div>
  );
}
